### ISSUE TITLE
G sheet & submit API

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-ny#1]
Please can you create & connect a Google sheet for "New York"

orgid: nyd

http://prntscr.com/ibasgr

**Comment by KNLopez** [comment]
Done

**Comment by jenbrannstrom** [comment]
Please add the Google sheet link here

**Comment by KNLopez** [comment]
https://docs.google.com/spreadsheets/d/1KLjzxcHFPAltoq6vAbt6tdKHEbO_NH8KvmoK4Hk2sko/edit?usp=sharing
