### ISSUE TITLE
AdWods conv tracking code

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-ny#2]
` 
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-1019641580"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-1019641580');
</script> `

and click event:

` 
<script>
function gtag_report_conversion(url) {
  var callback = function () {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  };
  gtag('event', 'conversion', {
      'send_to': 'AW-1019641580/3-O5CO2GinwQ7P2Z5gM',
      'event_callback': callback
  });
  return false;
}
</script> `

**Comment by KNLopez** [comment]
added
