### ISSUE TITLE
Failed submission

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-ny#3]
On trying submission on : http://oca.brainfree.info/

I get
http://prntscr.com/ic9141

"Validation error, please try again. If this error persists, please contact the site administrator. #1518166209-800058674"

Then it auto-redirects to https://www.oxfordcapacityanalysis.org/

**Comment by jenbrannstrom** [comment]
@KNLopez this is still failing:
http://prntscr.com/icwbyb

Also , it's live on Adwords since Wednesday morning - and still ZERO submissions have been entered into the sheet. This is highly unusual, since the other pages are working fine.
This is really unlikely: http://prntscr.com/icwdzg

**Comment by KNLopez** [comment]
Hi @jen, are we using the /ny directory for the repo?

**Comment by jenbrannstrom** [comment]
no no, look here:
http://prntscr.com/ie07nr
